### PR TITLE
Highlight Main Menu Items

### LINKED ISSUE #29: Main Navigation Menu Not Highlighting Correctly
# Issue Overview
The main navigation menu in sites running our theme is not highlighting the top-level items when a sub-item has been selected.

## Steps to reproduce?

1. Visit the theme reference site at [https://asu-wp2020-theme.rtd.asu.edu](https://asu-wp2020-theme.rtd.asu.edu)
2. Click on the 'Components' top-level menu item. Note that 'Components' is now underlined as the active menu item
3. From the drop-down menu that appears, select 'Buttons'
4. Notice that 'Components' is no longer highlighted as the active menu item when we are viewing a child page

## Expected behavior
I believe the expected Web Standards 2.0 behavior would be to have the top-level menu item (ex. 'Components') maintain the gold underline as the 'active' menu item when any sub-item is selected

### PR DESCRIPTION
**Pull request by wmcconnell**
Resolves #29 

Updates to our menu creation/rendering to apply the appropriate classes to top-level navigation items based on the current page, resulting in properly highlighted menu items. 

Changes in this pull request include:

- modified the existing method `uds_wp_get_menu_depth()` to not only return the depth of a current top-level menu item (single, children, or grandchildren), but to also include whether or not the top-level menu item, or any of its children, has a URL that matches the current URL
- modified the link rendering methods to apply the UDS class of 'active' to any top-level menu when there is a URL match with itself or any of its children
- code and comment cleanup based on PHPCS messages. This mostly concerned PHPDOC comment issues, the alignment of equals signs, and some escaping/sanitization of output.

I'm not entirely confident about the method I used to determine the current page's URL. I borrowed it from [this article](https://pwharton.co.uk/blog/wordpress-get-current-url/). I welcome any suggestions that would make the method as robust as possible. As it stands, I have not encountered any issues on my local copy of the Reference site.

### CODE REVIEW

**Comment by wmcconnell** [comment]
Pushed a new commit right after opening this PR because I had not considered recent updates to the develop branch. Merged the latest develop into my branch. No conflicts.

**Review by nathan-rollins — APPROVED** [review]
Looks good to me. Nice job!

File: asu-navigation-menu.php [hunk 1]
```diff
@@ -8,38 +8,73 @@
...
+	 */
+
+	// get an array for this menu item, and assign the depth to a local variable.
+	// early attempts to use switch() with $item_data array values did not work.
+	$item_data     = uds_wp_get_menu_depth( $item, $current_uri );
+	$item['depth'] = $item_data['depth'];
+
+	// set the CSS classname for this top-level item.
+	if ( $item_data['has_current'] ) {
+		$current_class = ' active';
```
Comment (zainabD) [inline asu-navigation-menu.php:43]: I would remove the space before ' active'

File: inc/wp-custom-menu.php [hunk 2]
```diff
@@ -75,7 +75,6 @@ function uds_wp_get_menu_formatted_array( $menu_name ) {
 					$menu[ $top_menu ]['children'][ $m->menu_item_parent ]['children'][ $m->ID ] = $column[ $m->ID ];
```
Comment (zainabD) [inline inc/wp-custom-menu.php:75]: Got some errors when tries to move some items one level down "as grandchild": 
Undefined index: parent in /app/wp-content/themes/UDS-WordPress-Theme/inc/wp-custom-menu.php on line 74
Undefined index: title in /app/wp-content/themes/UDS-WordPress-Theme/inc/wp-custom-menu.php on line 114 
Undefined index: url in /app/wp-content/themes/UDS-WordPress-Theme/inc/wp-custom-menu.php on line 122 
Undefined index: url in /app/wp-content/themes/UDS-WordPress-Theme/inc/wp-custom-menu.php on line 139 
Undefined index: cta_button in /app/wp-content/themes/UDS-WordPress-Theme/asu-navigation-menu.php on line 49 
Undefined index: cta_color in /app/wp-content/themes/UDS-WordPress-Theme/asu-navigation-menu.php on line 50
Undefined index: url in /app/wp-content/themes/UDS-WordPress-Theme/inc/wp-custom-menu.php on line 223 
Undefined index: title in /app/wp-content/themes/UDS-WordPress-Theme/inc/wp-custom-menu.php on line 223

**Review by zainabD — CHANGES_REQUESTED** [review]

File: asu-navigation-menu.php (hunk 1 above)
Comment (wmcconnell) [reply asu-navigation-menu.php]: Pushed a new commit that removes this space

File: inc/wp-custom-menu.php (hunk 2 above)
Comment (wmcconnell) [reply inc/wp-custom-menu.php:75]: It looks like Zainab discovered a bug with our menu code here that's outside the scope of this PR for highlighting top level items (in fact, the top-level highlighting still works even though the errors appear in the menu!). I'm going to create a new issue in the project for handling this and go ahead and merge this PR so that we tackle this issue on an updated codebase.

**Review by zainabD — APPROVED** [review]
